// <auto-generated />
namespace IT_Department_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addDeviceMovementsTableAndItsRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDeviceMovementsTableAndItsRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "201910140636447_addDeviceMovementsTableAndItsRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
