// <auto-generated />
namespace IT_Department_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ta3deel3a4anY4tagal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ta3deel3a4anY4tagal));
        
        string IMigrationMetadata.Id
        {
            get { return "201910141006110_ta3deel3a4anY4tagal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
